---
title: "GSI Grade Graphing"
output: html_document
date: "2024-06-07"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)


GSI_data <- read.csv("Grades - combined.csv")
GSI_data$Collection.Date <- as.Date(GSI_data$Collection.Date, format = "%m/%d/%Y")
GSI_data$Date_Site <- factor(paste(GSI_data$Collection.Date, GSI_data$Site, sep = "_"))
date_breaks <- as.numeric(as.Date(unique(GSI_data$Collection.Date))) #makes the x-axis formatted right

GSI_plot <- ggplot(GSI_data, aes(x = Collection.Date, y = Num.Grade, fill = Site)) +
  geom_boxplot(aes(group = Date_Site), width = 7) +
  labs(y = "Grade", x = "Collection Date", fill = "Site") +
  ggtitle("GSI Over Time At Arroyo Quemado and Mohawk Reef") +
  scale_y_continuous(limits = c(0.5, 6)) +
  #geom_smooth(data = subset(GSI_data, Site == "ARQ"), method = "loess", color = "black", linetype = "dashed", aes(group = Site), linewidth = 0.5, se = FALSE) +
  #geom_smooth(data = subset(GSI_data, Site == "Mohawk"), method = "loess", color = "black", linetype = "solid", aes(group = Site), linewidth = 0.5, se = FALSE) +
  scale_fill_manual(values = c("#F5DE31", "#EC7B23"),
                    name = "Site",
                    labels = c("Arroyo Quemado", "Mohawk Reef")) +
  theme(panel.background = element_rect(fill = "white"),
        plot.background = element_rect(fill = "white"),
        panel.grid.major = element_line(color = "gray", linewidth = 0.5),
        panel.grid.minor = element_blank(),
        plot.title = element_text(hjust = 0.5, size = 14, margin = margin(b = 20)),
        axis.text.x = element_text(size = 9)) +  
  scale_x_continuous(breaks = date_breaks, #whatever you do don't change this function because then everything doesn't work anymore D: (merges them all to two different box and whiskers)
                     labels = function(x) format(as.Date(x, origin = "1970-01-01"), "%m/%d/%y"), 
                     name = "Collection Date") +
  theme(axis.text.x = element_text(angle = 65, hjust = 1),
         axis.line = element_line(color = "black", linewidth = 0.5)) 

plot(GSI_plot)
```

```{r}

GSI_data <- read.csv("Grades - combined.csv")
GSI_data$Collection.Date <- as.Date(GSI_data$Collection.Date, format = "%m/%d/%Y")
GSI_data$Date_Site <- factor(paste(GSI_data$Collection.Date, GSI_data$Site, sep = "_"))

GSI_plot <- ggplot(GSI_data, aes(x = Date_Site, y = Num.Grade, fill = Site)) +
  geom_boxplot(lwd=0.2) +
  labs(y = "Grade Level", x = "Collection Date", fill = "Site") +
  ggtitle("GSI Over Time At Arroyo Quemado and Mohawk Reef") +
  scale_y_continuous(limits = c(0.5, 5)) +
   geom_smooth(data = subset(GSI_data, Site == "ARQ"), method = "loess", color = "black", linetype = "dashed", aes(group = Site), linewidth = 0.5, se = FALSE) +
  geom_smooth(data = subset(GSI_data, Site == "Mohawk"), method = "loess", color = "black", linetype = "solid", aes(group = Site), linewidth = 0.5, se = FALSE) +
  scale_fill_manual(values = c("#F5DE31", "#EC7B23"),
                    name = "Site",
                    labels = c("Arroyo Quemado", "Mohawk Reef")) +
  theme(panel.background = element_rect(fill = "white"),
        plot.background = element_rect(fill = "white"),
        panel.grid.major = element_line(color = "gray", linewidth = 0.5),
        panel.grid.minor = element_blank(),
        plot.title = element_text(hjust = 0.5, size = 14, margin = margin(b = 20))) +
  scale_x_discrete(labels = function(x) format(as.Date(x, "%Y-%m-%d"), "%m/%d/%y"), #not continuous x-axis 
                   breaks = unique(GSI_data$Date_Site), 
                   name = "Collection Date") + 
  theme(axis.text.x = element_text(angle = 35, hjust = 1)) 

print(GSI_plot)
```

```{r}
GSI_data <- read.csv("grades.csv")
GSI_data$Collection.Date <- as.Date(GSI_data$Collection.Date, format = "%m/%d/%Y")
GSI_data$Date_Site <- factor(paste(GSI_data$Collection.Date, GSI_data$Site, sep = "_"))

mean_sd_df <- aggregate(Numerical.Grade ~ Date_Site + Site, data = GSI_data, 
                        FUN = function(x) c(mean = mean(x), sd = sd(x)))

GSI_plot <- ggplot(mean_sd_df, aes(x = Date_Site, y = Numerical.Grade[, "mean"], fill = Site)) +
  geom_col(position = "dodge") +  # Use geom_col instead of geom_bar
  geom_errorbar(aes(ymin = Numerical.Grade[, "mean"] - Numerical.Grade[, "sd"], 
                    ymax = Numerical.Grade[, "mean"] + Numerical.Grade[, "sd"]), 
                position = position_dodge(width = 0.9),  # Adjust width as needed
                width = 0.25) +  # Adjust width of error bars as needed
  labs(y = "Grade Level", x = "Collection Date", fill = "Site") +
  ggtitle("GSI Over Time At Arroyo Quemado and Mohawk Reef") +
  scale_y_continuous(limits = c(0.5, 6)) +
  scale_fill_manual(values = c("#F5DE31", "#EC7B23"),
                    name = "Site",
                    labels = c("Arroyo Quemado", "Mohawk Reef")) +
  theme(panel.background = element_rect(fill = "white"),
        plot.background = element_rect(fill = "white"),
        panel.grid.major = element_line(color = "gray", linewidth = 0.5),
        panel.grid.minor = element_blank(),
        plot.title = element_text(hjust = 0.5, size = 14, margin = margin(b = 20))) +
  scale_x_discrete(labels = function(x) format(as.Date(x, "%Y-%m-%d"), "%m/%d/%y"), 
                   breaks = unique(GSI_data$Date_Site), 
                   name = "Collection Date") + 
  theme(axis.text.x = element_text(angle = 35, hjust = 1))

print(GSI_plot)

colnames(mean_sd_df)
```


```{r}
Mohawk_grades <- read.csv("Grades - MH.csv")
time_points <- unique(Mohawk_grades$Collection.Date)

mean_sd_df <- data.frame(Collection.Date = time_points,
                         Mean_Num.Grade = tapply(Mohawk_grades$Num.Grade, INDEX = Mohawk_grades$Collection.Date, mean),
                         SD_Num.Grade = tapply(Mohawk_grades$Num.Grade, Mohawk_grades$Collection.Date, sd))

Mohawk_plot <- ggplot(mean_sd_df, aes(x = Collection.Date, y = Mean_Num.Grade)) +
  geom_bar(stat = "identity", fill = "#F5DE31", width = 0.5) +
  geom_errorbar(aes(ymin = Mean_Num.Grade - SD_Num.Grade, ymax = Mean_Num.Grade + SD_Num.Grade), 
                width = 0.1, color = "black", linewidth = 0.5) +
  labs(y = "Grade Levels", x = "Collection Date") +
  scale_y_continuous(limits = c(0, 5)) +
  ggtitle("Grade Levels Over Time At Mohawk Reef") + 
  theme(panel.background = element_rect(fill = "white"),
        plot.background = element_rect(fill = "white"),
        panel.grid.major = element_line(color = "gray", linewidth = 0.5),
        panel.grid.minor = element_blank(),
        plot.title = element_text(hjust = 0.5, size = 14, margin = margin(b = 20)))

Mohawk_plot
```

```{r}
AR_grades <- read.csv("Grades - AR.csv")
time_points <- unique(AR_grades$Collection.Date)

mean_sd_df <- data.frame(Collection.Date = time_points,
                         Mean_Numerical.Grade = tapply(AR_grades$Num.Grade, INDEX = AR_grades$Collection.Date, mean),
                         SD_Numerical.Grade = tapply(AR_grades$Num.Grade, AR_grades$Collection.Date, sd))

AR_plot <- ggplot(mean_sd_df, aes(x = Collection.Date, y = Mean_Numerical.Grade)) +
  geom_bar(stat = "identity", fill = "orange", width = 0.5) +
  geom_errorbar(aes(ymin = Mean_Numerical.Grade - SD_Numerical.Grade, ymax = Mean_Numerical.Grade + SD_Numerical.Grade), 
                width = 0.1, color = "black", linewidth = 0.5) +
  labs(y = "Grade Level", x = "Collection Date") +
  scale_y_continuous(limits = c(0, 5)) +
  ggtitle("Grades Over Time At Arroyo Quemado") + 
  theme(panel.background = element_rect(fill = "white"),
        plot.background = element_rect(fill = "white"),
        panel.grid.major = element_line(color = "gray", linewidth = 0.5),
        panel.grid.minor = element_blank(),
        plot.title = element_text(hjust = 0.5, size = 14, margin = margin(b = 20)))

AR_plot
```

```{r}
library(gridExtra)
combined_plots <- grid.arrange(AR_plot, Mohawk_plot, nrow = 1)
print(combined_plots)
```




