---
title: "GSI mappings"
author: "Sophia Cabral :D "
date: "2024-04-17"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(gridExtra)
```

```{r Mohawk bar}
Mohawk_data <- read.csv("Mohawk.csv")
time_points <- unique(Mohawk_data$Collection.Date)

mean_sd_df <- data.frame(Collection.Date = time_points,
                         Mean_GSI = tapply(Mohawk_data$GSI, Mohawk_data$Collection.Date, mean),
                         SD_GSI = tapply(Mohawk_data$GSI, Mohawk_data$Collection.Date, sd))

Mohawk_plot <- ggplot(mean_sd_df, aes(x = Collection.Date, y = Mean_GSI)) +
  geom_bar(stat = "identity", fill = "#F5DE31", width = 0.5) +
  geom_errorbar(aes(ymin = Mean_GSI - SD_GSI, ymax = Mean_GSI + SD_GSI), 
                width = 0.1, color = "black", linewidth = 0.5) +
  labs(y = "Gonadosomatic Index", x = "Collection Date") +
  scale_y_continuous(limits = c(0, 0.15)) +
  ggtitle("GSI Over Time At Mohawk Beach") + 
  theme(panel.background = element_rect(fill = "white"),
        plot.background = element_rect(fill = "white"),
        panel.grid.major = element_line(color = "gray", linewidth = 0.5),
        panel.grid.minor = element_blank(),
        plot.title = element_text(hjust = 0.5, size = 14, margin = margin(b = 20)))

print(Mohawk_plot)
```
```{r ARQ bar}
ARQ_data <- read.csv("Arroyo.csv")
time_points <- unique(ARQ_data$Collection.Date)


mean_sd_df <- data.frame(Collection.Date = time_points,
                         Mean_GSI = tapply(ARQ_data$GSI, ARQ_data$Collection.Date, mean),
                         SD_GSI = tapply(ARQ_data$GSI, ARQ_data$Collection.Date, sd))

ARQ_plot <- ggplot(mean_sd_df, aes(x = Collection.Date, y = Mean_GSI)) +
  geom_bar(stat = "identity", fill = "#EC7B23", width = 0.5) +
  geom_errorbar(aes(ymin = Mean_GSI - SD_GSI, ymax = Mean_GSI + SD_GSI), 
                width = 0.1, color = "black", linewidth = 0.5) +
  labs(y = "Gonadosomatic Index", x = "Collection Date") +
  scale_y_continuous(limits = c(0, 0.15)) +
  ggtitle("GSI Over Time At ARQ") + 
  theme(panel.background = element_rect(fill = "white"),
        plot.background = element_rect(fill = "white"),
        panel.grid.major = element_line(color = "gray", linewidth = 0.5),
        panel.grid.minor = element_blank(),
        plot.title = element_text(hjust = 0.5, size = 14, margin = margin(b = 20)))

print(ARQ_plot)
```




```{r Mohawk whisker plot}
library(ggplot2)

#Mohawk_data$Collection.Date <- as.Date(Mohawk_data$Collection.Date)
time_points <- unique(Mohawk_data$Collection.Date)

mean_sd_df <- data.frame(Collection.Date = time_points,
                         Mean_GSI = tapply(Mohawk_data$GSI, Mohawk_data$Collection.Date, mean),
                         SD_GSI = tapply(Mohawk_data$GSI, Mohawk_data$Collection.Date, sd))

MohawkW_plot <- ggplot(Mohawk_data, aes(x = Collection.Date, y = GSI)) +
  geom_boxplot(fill = "#F5DE31", width = 0.5, outlier.shape = NA) + 
  geom_smooth(method = "loess", se = FALSE, color = "black", linewidth = 1.5) + 
  labs(y = "Gonadosomatic Index", x = "Collection Date") +
  scale_y_continuous(limits = c(0, 0.15)) +
  ggtitle("GSI Over Time At Mohawk Reef") + 
  theme(panel.background = element_rect(fill = "white"),
        plot.background = element_rect(fill = "white"),
        panel.grid.major = element_line(color = "gray", linewidth = 0.5),
        panel.grid.minor = element_blank(),
        plot.title = element_text(hjust = 0.5, size = 14, margin = margin(b = 20)))

print(MohawkW_plot)
```

```{r ARQ whisker plot}
library(ggplot2)

time_points <- unique(ARQ_data$Collection.Date)

mean_sd_df <- data.frame(Collection.Date = time_points,
                         Mean_GSI = tapply(ARQ_data$GSI, ARQ_data$Collection.Date, mean),
                         SD_GSI = tapply(ARQ_data$GSI, ARQ_data$Collection.Date, sd))

ARQW_plot <- ggplot(ARQ_data, aes(x = Collection.Date, y = GSI)) +
  geom_boxplot(fill = "#EC7B23", width = 0.5, outlier.shape = NA) + 
  geom_smooth(method = "loess", se = FALSE, color = "black", linewidth = 1.5) + 
  labs(y = "Gonadosomatic Index", x = "Collection Date") +
  scale_y_continuous(limits = c(0, 0.15)) +
  ggtitle("GSI Over Time At Arroyo Quemado") + 
  theme(panel.background = element_rect(fill = "white"),
        plot.background = element_rect(fill = "white"),
        panel.grid.major = element_line(color = "gray", linewidth = 0.5),
        panel.grid.minor = element_blank(),
        plot.title = element_text(hjust = 0.5, size = 14, margin = margin(b = 20)))

print(ARQW_plot)
```

```{r side by side bar plot}
combined_plots <- grid.arrange(Mohawk_plot, ARQ_plot, nrow = 1)
print(combined_plots)
```

```{r data stats test}
library(ggplot2)
GSI_data <- read.csv("combined.csv")

GSI_data$GSI <- as.numeric(GSI_data$GSI)
ARQ_GSI <- GSI_data[GSI_data$Site == "ARQ", "GSI"]
Mohawk_GSI <- GSI_data[GSI_data$Site == "Mohawk", "GSI"]

#t-test
t_test_result <- t.test(ARQ_GSI, Mohawk_GSI)
print(t_test_result)

#ANOVA 
anova_result <- aov(GSI ~ Site, data = GSI_data)
summary(anova_result)

qqnorm(resid(anova_result))
  qqline(resid(anova_result))
  
GSI_data$log_value <- log(resid(anova_result))
hist(GSI_data$log_value, main = "Histogram of Log Values")
```


```{r side by side data}
combined_plots <- grid.arrange(MohawkW_plot, ARQW_plot, nrow = 1)
print(combined_plots)
```


```{r the chosen one (imagine sparkle emoji here)}

GSI_data <- read.csv("to plot.csv")
GSI_data$Collection.Date <- as.Date(GSI_data$Collection.Date, format = "%m/%d/%Y")
GSI_data$Date_Site <- factor(paste(GSI_data$Collection.Date, GSI_data$Site, sep = "_"))

GSI_plot <- ggplot(GSI_data, aes(x = Date_Site, y = GSI, fill = Site)) +
  geom_boxplot() +
  labs(y = "Gonadosomatic Index", x = "Collection Date", fill = "Site") +
  ggtitle("GSI Over Time At Arroyo Quemado and Mohawk Reef") +
  scale_y_continuous(limits = c(0, 0.2)) +
   geom_smooth(data = subset(GSI_data, Site == "ARQ"), method = "loess", color = "black", linetype = "dashed", aes(group = Site), linewidth = 0.5, se = FALSE) +
  geom_smooth(data = subset(GSI_data, Site == "Mohawk"), method = "loess", color = "black", linetype = "solid", aes(group = Site), linewidth = 0.5, se = FALSE) +
  scale_fill_manual(values = c("#F5DE31", "#EC7B23"),
                    name = "Site",
                    labels = c("Arroyo Quemado", "Mohawk Reef")) +
  theme(panel.background = element_rect(fill = "white"),
        plot.background = element_rect(fill = "white"),
        panel.grid.major = element_line(color = "gray", linewidth = 0.5),
        panel.grid.minor = element_blank(),
        plot.title = element_text(hjust = 0.5, size = 14, margin = margin(b = 20))) +
  scale_x_discrete(labels = function(x) format(as.Date(x, "%Y-%m-%d"), "%m/%d/%y"), #not continuous x-axis 
                   breaks = unique(GSI_data$Date_Site), 
                   name = "Collection Date") + 
  theme(axis.text.x = element_text(angle = 35, hjust = 1)) 

print(GSI_plot)
```

```{r with scaled x}
GSI_data <- read.csv("to plot.csv")
GSI_data$Collection.Date <- as.Date(GSI_data$Collection.Date, format = "%m/%d/%Y")
GSI_data$Date_Site <- factor(paste(GSI_data$Collection.Date, GSI_data$Site, sep = "_"))
date_breaks <- as.numeric(as.Date(unique(GSI_data$Collection.Date))) #makes the x-axis formatted right

GSI_plot <- ggplot(GSI_data, aes(x = Collection.Date, y = GSI, fill = Site)) +
  geom_boxplot(aes(group = Date_Site), width = 4) +
  labs(y = "Gonadosomatic Index", x = "Collection Date", fill = "Site") +
  ggtitle("GSI Over Time At Arroyo Quemado and Mohawk Reef") +
  scale_y_continuous(limits = c(0, 0.2)) +
  geom_smooth(data = subset(GSI_data, Site == "ARQ"), method = "loess", color = "black", linetype = "dashed", aes(group = Site), linewidth = 0.5, se = FALSE) +
  geom_smooth(data = subset(GSI_data, Site == "Mohawk"), method = "loess", color = "black", linetype = "solid", aes(group = Site), linewidth = 0.5, se = FALSE) +
  scale_fill_manual(values = c("#F5DE31", "#EC7B23"),
                    name = "Site",
                    labels = c("Arroyo Quemado", "Mohawk Reef")) +
  theme(panel.background = element_rect(fill = "white"),
        plot.background = element_rect(fill = "white"),
        panel.grid.major = element_line(color = "gray", linewidth = 0.5),
        panel.grid.minor = element_blank(),
        plot.title = element_text(hjust = 0.5, size = 14, margin = margin(b = 20)),
        axis.text.x = element_text(size = 9)) +  
  scale_x_continuous(breaks = date_breaks, #whatever you do don't change this function because then everything doesn't work anymore D: (merges them all to two different box and whiskers)
                     labels = function(x) format(as.Date(x, origin = "1970-01-01"), "%m/%d/%y"), 
                     name = "Collection Date") +
  theme(axis.text.x = element_text(angle = 65, hjust = 1),
         axis.line = element_line(color = "black", linewidth = 0.5)) 

print(GSI_plot)

ggsave("GSI_plot.png", GSI_plot, width = 12, height = 6)
```








